#!/usr/bin/env python
# _*_coding: utf-8 _*_
"""指标类型定义"""
METRIC_TYPE_CPU = "cpu"
METRIC_TYPE_MEMORY = "memory"
METRIC_TYPE_DISK = "disk"
METRIC_TYPE_NETWORK = "network"
METRIC_TYPES = [METRIC_TYPE_CPU, METRIC_TYPE_MEMORY, METRIC_TYPE_DISK, METRIC_TYPE_NETWORK]
